apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-tasks
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/instances/namespace-staging/tasks
    repoURL: https://github.com/viecili/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2-viecili
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
